apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bse-monitor
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - image: gcr.io/YOUR_PROJECT_ID/bse-monitor
        env:
        - name: TZ
          value: "Asia/Kolkata"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
