[build]
builder = "nixpacks"

[deploy]
startCommand = "python bse_monitor.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "bse-monitor"
